apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: sample-workspace
spec:
  providerConfigRef:
    name: aws-irsa
  forProvider:
    source: Inline
    module: |
      resource "aws_vpc" "main" {
        cidr_block = "10.1.0.0/16"

        tags = {
          Name = "${var.eks_cluster_name}"
        }
      }
    vars:
      - key: eks_cluster_name
        value: "codefresh-demo-environment"
